#!/usr/bin/env python3
"""Generate acf-json/group_rutherford_recovery_fest_page.json"""
import json, os

data = {
    "key": "group_rutherford_recovery_fest_page",
    "title": "Rutherford Recovery Fest Page",
    "fields": [
        # TAB: Intro
        {"key":"field_rrf_tab_intro","label":"Intro Section","name":"","aria-label":"","type":"tab","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":0,"placement":"top","endpoint":0,"selected":0},
        {"key":"field_rrf_intro_badge","label":"Badge Text","name":"rrf_intro_badge","aria-label":"","type":"text","instructions":"Small label above the heading, e.g. \"10th Annual Event\".","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":1,"default_value":"10th Annual Event","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_intro_heading","label":"Section Heading","name":"rrf_intro_heading","aria-label":"","type":"text","instructions":"Main <h2> heading. Leave blank to hide the entire intro section.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":2,"default_value":"Celebrating Recovery, Inspiring Hope","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_intro_subtitle","label":"Subtitle Paragraph","name":"rrf_intro_subtitle","aria-label":"","type":"textarea","instructions":"Short subtitle rendered below the heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":3,"default_value":"Rutherford Recovery Fest is a free, family-friendly annual event hosted by PC4S to end the stigma around mental health and substance use disorders in Rutherford County.","placeholder":"","maxlength":"","rows":3,"new_lines":"br"},
        {"key":"field_rrf_intro_lead","label":"Lead Paragraph","name":"rrf_intro_lead","aria-label":"","type":"textarea","instructions":"Longer body paragraph. Supports basic HTML via wp_kses_post (e.g. <strong>).","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":4,"default_value":"Our mission is to <strong>Educate</strong> the public on mental health and substance use disorders, <strong>Equip</strong> the community through educational resources and shared experiences, and <strong>Expand</strong> our influence through community outreach. Join us for exhibitors, speakers, testimonials, music, food, and activities for kids.","placeholder":"","maxlength":"","rows":4,"new_lines":"br"},
        {"key":"field_rrf_intro_cta_primary","label":"Primary CTA Button","name":"rrf_intro_cta_primary","aria-label":"","type":"link","instructions":"Primary action button (e.g. \"Event Documents\" \u2192 #rrf-documents).","required":0,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":5,"return_format":"array"},
        {"key":"field_rrf_intro_cta_secondary","label":"Secondary CTA Button","name":"rrf_intro_cta_secondary","aria-label":"","type":"link","instructions":"Secondary (outline) button (e.g. \"Get Involved\" \u2192 /contact-us/).","required":0,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":6,"return_format":"array"},
        {"key":"field_rrf_intro_card_heading","label":"Event Card Heading","name":"rrf_intro_card_heading","aria-label":"","type":"text","instructions":"Heading inside the right-hand event details card.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":7,"default_value":"2026 Event Details","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_intro_card_details","label":"Event Detail Rows","name":"rrf_intro_card_details","aria-label":"","type":"repeater","instructions":"Each row is one detail line (icon + text) in the event card.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":8,"layout":"table","min":0,"max":6,"collapsed":"","button_label":"Add Detail Row","sub_fields":[
            {"key":"field_rrf_detail_icon","label":"Icon","name":"rrf_detail_icon","aria-label":"","type":"select","instructions":"Icon displayed alongside the detail text.","required":0,"conditional_logic":0,"wrapper":{"width":"25","class":"","id":""},"order_no":0,"choices":{"calendar":"Calendar","location":"Location Pin","clock":"Clock","ticket":"Ticket"},"default_value":"calendar","return_format":"value","allow_null":0,"multiple":0,"ui":0,"ajax":0,"placeholder":""},
            {"key":"field_rrf_detail_text","label":"Detail Text","name":"rrf_detail_text","aria-label":"","type":"text","instructions":"Text for this detail row. Supports links via wp_kses_post.","required":0,"conditional_logic":0,"wrapper":{"width":"75","class":"","id":""},"order_no":1,"default_value":"","placeholder":"e.g. Date & Time to be announced","prepend":"","append":"","maxlength":""}
        ]},
        {"key":"field_rrf_intro_card_note","label":"Sponsorship Contact Note","name":"rrf_intro_card_note","aria-label":"","type":"textarea","instructions":"Note at the bottom of the event card (after a divider). Supports basic HTML links.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":9,"default_value":"For sponsorship inquiries, contact <strong>Sarah Murfree</strong> at <a href=\"tel:629-278-9078\" style=\"color:hsl(0,85%,92%);text-underline-offset:0.2em\">629-278-9078</a> or visit <a href=\"https://www.pc4s.org\" target=\"_blank\" rel=\"noopener noreferrer\" style=\"color:hsl(0,85%,92%);text-underline-offset:0.2em\">pc4s.org</a>. Donations to PC4S, a 501(c)(3), are tax deductible.","placeholder":"","maxlength":"","rows":4,"new_lines":"br"},

        # TAB: Highlights
        {"key":"field_rrf_tab_highlights","label":"Event Highlights","name":"","aria-label":"","type":"tab","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":10,"placement":"top","endpoint":0,"selected":0},
        {"key":"field_rrf_highlights_badge","label":"Badge Text","name":"rrf_highlights_badge","aria-label":"","type":"text","instructions":"Small label above the highlights heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":11,"default_value":"What to Expect","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_highlights_heading","label":"Section Heading","name":"rrf_highlights_heading","aria-label":"","type":"text","instructions":"Main <h2> heading for the highlights section.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":12,"default_value":"Something for Everyone","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_highlights_subtitle","label":"Subtitle","name":"rrf_highlights_subtitle","aria-label":"","type":"textarea","instructions":"Short description below the highlights heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":13,"default_value":"Rutherford Recovery Fest brings together the community with music, resources, family activities, and the power of shared stories.","placeholder":"","maxlength":"","rows":3,"new_lines":"br"},
        {"key":"field_rrf_highlights","label":"Highlight Items","name":"rrf_highlights","aria-label":"","type":"repeater","instructions":"Add each feature/highlight card shown in the grid.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":14,"layout":"block","min":0,"max":12,"collapsed":"","button_label":"Add Highlight","sub_fields":[
            {"key":"field_rrf_highlight_icon","label":"Icon","name":"rrf_highlight_icon","aria-label":"","type":"select","instructions":"Choose the icon for this highlight card.","required":0,"conditional_logic":0,"wrapper":{"width":"30","class":"","id":""},"order_no":0,"choices":{"music":"Music Note","resources":"Resource Tables (House)","family":"Family / People","story":"Recovery Stories (Heart)","speaker":"Speakers / Headphones","food":"Food","default":"Generic Circle"},"default_value":"default","return_format":"value","allow_null":0,"multiple":0,"ui":0,"ajax":0,"placeholder":""},
            {"key":"field_rrf_highlight_label","label":"Label","name":"rrf_highlight_label","aria-label":"","type":"text","instructions":"Short card heading, e.g. \"Live Music\".","required":0,"conditional_logic":0,"wrapper":{"width":"70","class":"","id":""},"order_no":1,"default_value":"","placeholder":"e.g. Live Music","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_highlight_desc","label":"Description","name":"rrf_highlight_desc","aria-label":"","type":"textarea","instructions":"Short description below the card label.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":2,"default_value":"","placeholder":"","maxlength":"","rows":2,"new_lines":"br"}
        ]},

        # TAB: Documents
        {"key":"field_rrf_tab_docs","label":"Documents & Sign-Ups","name":"","aria-label":"","type":"tab","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":15,"placement":"top","endpoint":0,"selected":0},
        {"key":"field_rrf_docs_badge","label":"Badge Text","name":"rrf_docs_badge","aria-label":"","type":"text","instructions":"Small label above the documents heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":16,"default_value":"2026 Resources","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_docs_heading","label":"Section Heading","name":"rrf_docs_heading","aria-label":"","type":"text","instructions":"Main <h2> heading for the documents section.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":17,"default_value":"Documents & Sign-Ups","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_docs_subtitle","label":"Subtitle","name":"rrf_docs_subtitle","aria-label":"","type":"textarea","instructions":"Short description below the documents heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":18,"default_value":"Download the 2026 sponsorship packet or reserve your resource table at Rutherford Recovery Fest on Eventbrite.","placeholder":"","maxlength":"","rows":3,"new_lines":"br"},
        {"key":"field_rrf_docs_cards","label":"Document Cards","name":"rrf_docs_cards","aria-label":"","type":"repeater","instructions":"Each card links to an external URL (Google Drive, Eventbrite, etc.).","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":19,"layout":"block","min":0,"max":6,"collapsed":"","button_label":"Add Document Card","sub_fields":[
            {"key":"field_rrf_doc_icon","label":"Card Icon","name":"rrf_doc_icon","aria-label":"","type":"select","instructions":"Icon displayed in the card header.","required":0,"conditional_logic":0,"wrapper":{"width":"25","class":"","id":""},"order_no":0,"choices":{"document":"PDF / Document","calendar":"Calendar / Event","link":"External Link","default":"Generic"},"default_value":"document","return_format":"value","allow_null":0,"multiple":0,"ui":0,"ajax":0,"placeholder":""},
            {"key":"field_rrf_doc_tag","label":"Tag Label","name":"rrf_doc_tag","aria-label":"","type":"text","instructions":"Small badge label, e.g. \"PDF Document\" or \"Eventbrite\".","required":0,"conditional_logic":0,"wrapper":{"width":"25","class":"","id":""},"order_no":1,"default_value":"PDF Document","placeholder":"","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_doc_title","label":"Card Title","name":"rrf_doc_title","aria-label":"","type":"text","instructions":"Card heading text.","required":1,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":2,"default_value":"","placeholder":"e.g. 2026 Sponsorship Information","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_doc_desc","label":"Card Description","name":"rrf_doc_desc","aria-label":"","type":"textarea","instructions":"Short description shown on the card body.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":3,"default_value":"","placeholder":"","maxlength":"","rows":3,"new_lines":"br"},
            {"key":"field_rrf_doc_cta_label","label":"CTA Label","name":"rrf_doc_cta_label","aria-label":"","type":"text","instructions":"Text for the CTA, e.g. \"Download PDF\" or \"Sign Up on Eventbrite\".","required":0,"conditional_logic":0,"wrapper":{"width":"30","class":"","id":""},"order_no":4,"default_value":"Download","placeholder":"","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_doc_url","label":"Document URL","name":"rrf_doc_url","aria-label":"","type":"url","instructions":"Full URL for the document or sign-up (Google Drive, Eventbrite, etc.). Must be publicly accessible.","required":1,"conditional_logic":0,"wrapper":{"width":"70","class":"","id":""},"order_no":5,"default_value":"","placeholder":"https://drive.google.com/file/d/..."}
        ]},

        # TAB: Sponsors
        {"key":"field_rrf_tab_sponsor","label":"Sponsor Tiers","name":"","aria-label":"","type":"tab","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":20,"placement":"top","endpoint":0,"selected":0},
        {"key":"field_rrf_sponsor_badge","label":"Badge Text","name":"rrf_sponsor_badge","aria-label":"","type":"text","instructions":"Small label above the sponsor heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":21,"default_value":"Support the Fest","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_sponsor_heading","label":"Section Heading","name":"rrf_sponsor_heading","aria-label":"","type":"text","instructions":"Main <h2> heading for the sponsor section.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":22,"default_value":"Become a Sponsor","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_sponsor_subtitle","label":"Subtitle / Details","name":"rrf_sponsor_subtitle","aria-label":"","type":"wysiwyg","instructions":"Paragraph below the heading. Supports links (phone, website).","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":23,"default_value":"<p>Help make Rutherford Recovery Fest possible. To pay by check, mail to PC4S at 630 Broadmor Blvd., Suite 130, Murfreesboro, TN 37129. To pay by card, visit <a href=\"https://www.pc4s.org\" target=\"_blank\" rel=\"noopener noreferrer\">pc4s.org</a> and click the \u201cDonate\u201d link. Contact <strong>Sarah Murfree</strong> at <a href=\"tel:629-278-9078\">629-278-9078</a> for more info.</p>","tabs":"all","toolbar":"basic","media_upload":0,"delay":0},
        {"key":"field_rrf_sponsor_tiers","label":"Sponsorship Tiers","name":"rrf_sponsor_tiers","aria-label":"","type":"repeater","instructions":"Add each sponsorship tier (Bronze, Silver, Gold, Platinum). Perks: one perk per line.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":24,"layout":"block","min":0,"max":8,"collapsed":"","button_label":"Add Tier","sub_fields":[
            {"key":"field_rrf_tier_name","label":"Tier Name","name":"rrf_tier_name","aria-label":"","type":"text","instructions":"e.g. \"Bronze Level\"","required":1,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":0,"default_value":"","placeholder":"e.g. Bronze Level","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_tier_price","label":"Price","name":"rrf_tier_price","aria-label":"","type":"text","instructions":"e.g. \"$500\"","required":0,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":1,"default_value":"","placeholder":"e.g. $500","prepend":"","append":"","maxlength":""},
            {"key":"field_rrf_tier_perks","label":"Perks (one per line)","name":"rrf_tier_perks","aria-label":"","type":"textarea","instructions":"Enter each perk on a separate line. Each line becomes one bullet item.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":2,"default_value":"","placeholder":"Company logo on promotional material\nPremium exhibit space","maxlength":"","rows":5,"new_lines":""},
            {"key":"field_rrf_tier_cta","label":"CTA Button","name":"rrf_tier_cta","aria-label":"","type":"link","instructions":"Button at the bottom of the tier card (e.g. \"Sponsor Now\" \u2192 /contact-us/).","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":3,"return_format":"array"}
        ]},

        # TAB: CTA
        {"key":"field_rrf_tab_cta","label":"CTA Section","name":"","aria-label":"","type":"tab","instructions":"","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":25,"placement":"top","endpoint":0,"selected":0},
        {"key":"field_rrf_cta_badge","label":"Badge Text","name":"rrf_cta_badge","aria-label":"","type":"text","instructions":"Small label above the CTA heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":26,"default_value":"Join the Movement","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_cta_heading","label":"CTA Heading","name":"rrf_cta_heading","aria-label":"","type":"text","instructions":"Main <h2> heading for the CTA section. Leave blank to hide.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":27,"default_value":"See You at the Fest!","placeholder":"","prepend":"","append":"","maxlength":""},
        {"key":"field_rrf_cta_subtitle","label":"Subtitle","name":"rrf_cta_subtitle","aria-label":"","type":"textarea","instructions":"Short paragraph below the CTA heading.","required":0,"conditional_logic":0,"wrapper":{"width":"","class":"","id":""},"order_no":28,"default_value":"Whether you attend, volunteer, sponsor, or set up a resource table \u2014 your presence makes Rutherford Recovery Fest stronger for everyone.","placeholder":"","maxlength":"","rows":3,"new_lines":"br"},
        {"key":"field_rrf_cta_primary","label":"Primary CTA Button","name":"rrf_cta_primary","aria-label":"","type":"link","instructions":"Primary action button (e.g. \"Get Involved\" \u2192 /contact-us/).","required":0,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":29,"return_format":"array"},
        {"key":"field_rrf_cta_secondary","label":"Secondary CTA Button","name":"rrf_cta_secondary","aria-label":"","type":"link","instructions":"Secondary (outline) button (e.g. \"View All Events\" \u2192 /events/).","required":0,"conditional_logic":0,"wrapper":{"width":"50","class":"","id":""},"order_no":30,"return_format":"array"}
    ],
    "location": [[{"param":"page_template","operator":"==","value":"templates/rutherford-recovery-fest-page.php"}]],
    "menu_order": 8,
    "position": "normal",
    "style": "default",
    "label_placement": "top",
    "instruction_placement": "label",
    "hide_on_screen": ["the_content","excerpt","discussion","comments","revisions","slug","author","format","categories","tags","send-trackbacks"],
    "active": True,
    "description": "Fields for the Rutherford Recovery Fest page template. The Sponsorship Information card URL should be a Google Drive link.",
    "show_in_rest": 0,
    "display_title": "",
    "modified": 1741132800
}

out = os.path.join(os.path.dirname(__file__), '..', 'acf-json', 'group_rutherford_recovery_fest_page.json')
out = os.path.normpath(out)
with open(out, 'w') as f:
    json.dump(data, f, indent='\t', ensure_ascii=False)
    f.write('\n')

# round-trip verify
with open(out) as f:
    json.load(f)

print(f'OK: {out}  ({os.path.getsize(out)} bytes)')
